import type { Metadata } from "next";

import "./globals.css";
import ConvexClientProvider from "@/components/provider/ConvexClientProvider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`antialiased bg-white`} cz-shortcut-listen="true"
      >

        <ConvexClientProvider>
        {children}
        </ConvexClientProvider>

      </body>
    </html>
  );
}
